/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package atm_machine;

import java.sql.*;
import java.sql.DriverManager;
import javax.swing.*;

/**
 *
 * @author 91975
 */
public class Checking extends javax.swing.JDialog {

    /**
     * Creates new form Checking
     */
    public Checking(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        accountnumber = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cancel2 = new javax.swing.JButton();
        More3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 25)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ENTER YOUR ACCOUNT NUMBER ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 410, 50));

        accountnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountnumberActionPerformed(evt);
            }
        });
        getContentPane().add(accountnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 320, 41));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 25)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ENTER YOUR FOUR DIGIN PIN");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 370, -1));
        getContentPane().add(pin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 180, 41));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, -1, -1));

        cancel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm_machine/cancel.png"))); // NOI18N
        cancel2.setBorder(null);
        cancel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel2ActionPerformed(evt);
            }
        });
        getContentPane().add(cancel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 180, 70));

        More3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm_machine/More.png"))); // NOI18N
        More3.setBorder(null);
        More3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                More3ActionPerformed(evt);
            }
        });
        getContentPane().add(More3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 180, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm_machine/coverfourth.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accountnumberActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_accountnumberActionPerformed

    }// GEN-LAST:event_accountnumberActionPerformed

    private void cancel2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cancel2ActionPerformed
        System.exit(0);
    }// GEN-LAST:event_cancel2ActionPerformed

    private void More3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_More3ActionPerformed
        if (accountnumber.getText().length() <= 0 || pin.getText().length() <= 0) {
            JOptionPane.showMessageDialog(null, " Enter Valid Information");
        } else {

            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection(
                        "jdbc:mysql://localhost:3306/atm", "root",
                        "2412");
                Statement stm = con.createStatement();
                String query2 = "Select * from card where card_no = '" + accountnumber.getText() + "' and card_pin = '"
                        + pin.getText()
                        + "'";
                ResultSet rs = stm.executeQuery(query2);
                if (rs.next()) {

                    JOptionPane.showMessageDialog(null, " LOGIN SUCCESSFULLY");
                    new Second();
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(null, " Account_number and PIN is WRONG !!");
                    accountnumber.setText(null);
                    pin.setText(null);
                }
                con.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e, null, 0);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public Checking() {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Checking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Checking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Checking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Checking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Checking dialog = new Checking(new javax.swing.JFrame(), true);
                dialog.setLocation(620, 280);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton More3;
    private javax.swing.JTextField accountnumber;
    private javax.swing.JButton cancel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField pin;
    // End of variables declaration//GEN-END:variables
}
