/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package atm_machine;

/**
 *
 * @author 91975
 */
public class fourthfast extends javax.swing.JDialog {

    /**
     * Creates new form fourthfast
     */
    public fourthfast(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JTextField();
        balance = new javax.swing.JTextField();
        lasttransaction = new javax.swing.JTextField();
        cancel = new javax.swing.JButton();
        Confirm = new javax.swing.JButton();
        back = new javax.swing.JButton();
        tenthousand = new javax.swing.JButton();
        hundred = new javax.swing.JButton();
        twohundred = new javax.swing.JButton();
        fivehundred = new javax.swing.JButton();
        Onethousand = new javax.swing.JButton();
        twothousand = new javax.swing.JButton();
        threethousand = new javax.swing.JButton();
        fivethousand = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name.setBackground(new java.awt.Color(0, 0, 0));
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setBorder(null);
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 180, 40));

        balance.setBackground(new java.awt.Color(0, 0, 0));
        balance.setForeground(new java.awt.Color(255, 255, 255));
        balance.setBorder(null);
        balance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceActionPerformed(evt);
            }
        });
        getContentPane().add(balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 168, 40));

        lasttransaction.setBackground(new java.awt.Color(0, 0, 0));
        lasttransaction.setForeground(new java.awt.Color(255, 255, 255));
        lasttransaction.setBorder(null);
        getContentPane().add(lasttransaction, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 168, 40));

        cancel.setBackground(new java.awt.Color(0, 0, 0));
        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm_machine/cancel.png"))); // NOI18N
        cancel.setBorder(null);
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 760, 180, 50));

        Confirm.setIcon(new javax.swing.ImageIcon(
                "C:\\Users\\91975\\OneDrive\\Desktop\\MY_WORK\\ATM_Machine\\img\\confirm.png")); // NOI18N
        Confirm.setBorder(null);
        Confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmActionPerformed(evt);
            }
        });
        getContentPane().add(Confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 610, 150, 40));

        back.setIcon(
                new javax.swing.ImageIcon("C:\\Users\\91975\\OneDrive\\Desktop\\MY_WORK\\ATM_Machine\\img\\back.png")); // NOI18N
        back.setBorder(null);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 770, 140, 32));

        tenthousand.setBackground(new java.awt.Color(0, 0, 0));
        tenthousand.setFont(new java.awt.Font("Segoe UI", 3, 30)); // NOI18N
        tenthousand.setForeground(new java.awt.Color(255, 255, 255));
        tenthousand.setText("10000 /-");
        getContentPane().add(tenthousand, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 460, 190, 50));

        hundred.setBackground(new java.awt.Color(0, 0, 0));
        hundred.setFont(new java.awt.Font("Segoe UI", 3, 35)); // NOI18N
        hundred.setForeground(new java.awt.Color(255, 255, 255));
        hundred.setText("100 /-");
        getContentPane().add(hundred, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 190, 50));

        twohundred.setBackground(new java.awt.Color(0, 0, 0));
        twohundred.setFont(new java.awt.Font("Segoe UI", 3, 35)); // NOI18N
        twohundred.setForeground(new java.awt.Color(255, 255, 255));
        twohundred.setText("200 /-");
        twohundred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twohundredActionPerformed(evt);
            }
        });
        getContentPane().add(twohundred, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 190, 50));

        fivehundred.setBackground(new java.awt.Color(0, 0, 0));
        fivehundred.setFont(new java.awt.Font("Segoe UI", 3, 35)); // NOI18N
        fivehundred.setForeground(new java.awt.Color(255, 255, 255));
        fivehundred.setText("500 /-");
        fivehundred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fivehundredActionPerformed(evt);
            }
        });
        getContentPane().add(fivehundred, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 190, 50));

        Onethousand.setBackground(new java.awt.Color(0, 0, 0));
        Onethousand.setFont(new java.awt.Font("Segoe UI", 3, 34)); // NOI18N
        Onethousand.setForeground(new java.awt.Color(255, 255, 255));
        Onethousand.setText("1000 /-");
        getContentPane().add(Onethousand, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, 190, 50));

        twothousand.setBackground(new java.awt.Color(0, 0, 0));
        twothousand.setFont(new java.awt.Font("Segoe UI", 3, 33)); // NOI18N
        twothousand.setForeground(new java.awt.Color(255, 255, 255));
        twothousand.setText("2000 /-");
        getContentPane().add(twothousand, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 200, 190, 50));

        threethousand.setBackground(new java.awt.Color(0, 0, 0));
        threethousand.setFont(new java.awt.Font("Segoe UI", 3, 32)); // NOI18N
        threethousand.setForeground(new java.awt.Color(255, 255, 255));
        threethousand.setText("3000 /-");
        threethousand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threethousandActionPerformed(evt);
            }
        });
        getContentPane().add(threethousand, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 280, 190, -1));

        fivethousand.setBackground(new java.awt.Color(0, 0, 0));
        fivethousand.setFont(new java.awt.Font("Segoe UI", 3, 31)); // NOI18N
        fivethousand.setForeground(new java.awt.Color(255, 255, 255));
        fivethousand.setText("5000 /-");
        getContentPane().add(fivethousand, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 370, 190, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(
                "C:\\Users\\91975\\OneDrive\\Desktop\\MY_WORK\\ATM_Machine\\img\\coverthird1.jpg")); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 670, 470));

        jLabel1.setIcon(
                new javax.swing.ImageIcon("C:\\Users\\91975\\OneDrive\\Desktop\\MY_WORK\\ATM_Machine\\img\\Third.png")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void balanceActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_balanceActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_balanceActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cancelActionPerformed
        System.exit(0);
    }// GEN-LAST:event_cancelActionPerformed

    private void ConfirmActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ConfirmActionPerformed
        new Thankyou();
        dispose();
    }// GEN-LAST:event_ConfirmActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_backActionPerformed
        new Second();
        dispose();
    }// GEN-LAST:event_backActionPerformed

    private void twohundredActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_twohundredActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_twohundredActionPerformed

    private void threethousandActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_threethousandActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_threethousandActionPerformed

    private void fivehundredActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_fivehundredActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_fivehundredActionPerformed

    /**
     * @param args the command line arguments
     */
    public fourthfast() {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fourthfast.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fourthfast.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fourthfast.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fourthfast.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                fourthfast dialog = new fourthfast(new javax.swing.JFrame(), true);
                dialog.setLocation(370, 90);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Confirm;
    private javax.swing.JButton Onethousand;
    private javax.swing.JButton back;
    private javax.swing.JTextField balance;
    private javax.swing.JButton cancel;
    private javax.swing.JButton fivehundred;
    private javax.swing.JButton fivethousand;
    private javax.swing.JButton hundred;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField lasttransaction;
    private javax.swing.JTextField name;
    private javax.swing.JButton tenthousand;
    private javax.swing.JButton threethousand;
    private javax.swing.JButton twohundred;
    private javax.swing.JButton twothousand;
    // End of variables declaration//GEN-END:variables
}
