/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package atm_machine;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.swing.JOptionPane;

/**
 *
 * @author 91975
 */
public class Second extends javax.swing.JDialog {

    /**
     * Creates new form Second
     */
    public Second(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        balance = new javax.swing.JTextField();
        lasttransaction = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        ministatement = new javax.swing.JButton();
        fastcash = new javax.swing.JButton();
        withdrawal = new javax.swing.JButton();
        pinchange = new javax.swing.JButton();
        fundtransfer = new javax.swing.JButton();
        balanceenqury = new javax.swing.JButton();
        back = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        balance.setBackground(new java.awt.Color(0, 0, 0));
        balance.setForeground(new java.awt.Color(255, 255, 255));
        balance.setBorder(null);
        balance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceActionPerformed(evt);
            }
        });
        getContentPane().add(balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 168, 49));

        lasttransaction.setBackground(new java.awt.Color(0, 0, 0));
        lasttransaction.setForeground(new java.awt.Color(255, 255, 255));
        lasttransaction.setBorder(null);
        getContentPane().add(lasttransaction, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 168, 49));

        name.setBackground(new java.awt.Color(0, 0, 0));
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setBorder(null);
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 180, 49));

        ministatement.setIcon(new javax.swing.ImageIcon(
                "C:\\Users\\91975\\OneDrive\\Desktop\\MY_WORK\\ATM_Machine\\img\\ministatement.png")); // NOI18N
        ministatement.setBorder(null);
        ministatement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ministatementActionPerformed(evt);
            }
        });
        getContentPane().add(ministatement, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 460, 280, 210));

        fastcash.setIcon(new javax.swing.ImageIcon(
                "C:\\Users\\91975\\OneDrive\\Desktop\\MY_WORK\\ATM_Machine\\img\\fastcash.png")); // NOI18N
        fastcash.setBorder(null);
        fastcash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fastcashActionPerformed(evt);
            }
        });
        getContentPane().add(fastcash, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 291, -1));

        withdrawal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm_machine/withdrawals.png"))); // NOI18N
        withdrawal.setBorder(null);
        withdrawal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawalActionPerformed(evt);
            }
        });
        getContentPane().add(withdrawal, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 291, 210));

        pinchange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm_machine/Pinchange.png"))); // NOI18N
        pinchange.setBorder(null);
        pinchange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinchangeActionPerformed(evt);
            }
        });
        getContentPane().add(pinchange, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 220, 291, 210));

        fundtransfer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm_machine/FundTransfer.png"))); // NOI18N
        fundtransfer.setBorder(null);
        fundtransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fundtransferActionPerformed(evt);
            }
        });
        getContentPane().add(fundtransfer, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 290, 210));

        balanceenqury.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm_machine/balanceenqury.png"))); // NOI18N
        balanceenqury.setBorder(null);
        balanceenqury.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceenquryActionPerformed(evt);
            }
        });
        getContentPane().add(balanceenqury, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 460, 280, 210));

        back.setIcon(
                new javax.swing.ImageIcon("C:\\Users\\91975\\OneDrive\\Desktop\\MY_WORK\\ATM_Machine\\img\\back.png")); // NOI18N
        back.setBorder(null);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 710, 150, 32));

        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm_machine/cancel.png"))); // NOI18N
        cancel.setBorder(null);
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 770, 140, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(
                "C:\\Users\\91975\\OneDrive\\Desktop\\MY_WORK\\ATM_Machine\\img\\Dashboard.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ministatementActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ministatementActionPerformed
        new MiniStatement();
        dispose();
    }// GEN-LAST:event_ministatementActionPerformed

    private void pinchangeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_pinchangeActionPerformed
        new changePin();
        dispose();
    }// GEN-LAST:event_pinchangeActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cancelActionPerformed
        System.exit(0);
    }// GEN-LAST:event_cancelActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_backActionPerformed
        First f = new First();
        dispose();
    }// GEN-LAST:event_backActionPerformed

    private void balanceActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_balanceActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_balanceActionPerformed

    private void fastcashActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_fastcashActionPerformed
        new fourthfast();
        dispose();
    }// GEN-LAST:event_fastcashActionPerformed

    private void withdrawalActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_withdrawalActionPerformed
        new Third();
        dispose();
    }// GEN-LAST:event_withdrawalActionPerformed

    private void fundtransferActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_fundtransferActionPerformed
        new FundTransfer();
        dispose();
    }// GEN-LAST:event_fundtransferActionPerformed

    private void balanceenquryActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_balanceenquryActionPerformed
        new BalanceEnquiry();
        dispose();
    }// GEN-LAST:event_balanceenquryActionPerformed

    /**
     * @param args the command line arguments
     */
    public Second() {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Second.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Second.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Second.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Second.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Second dialog = new Second(new javax.swing.JFrame(), true);
                dialog.setLocation(370, 90);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextField balance;
    private javax.swing.JButton balanceenqury;
    private javax.swing.JButton cancel;
    private javax.swing.JButton fastcash;
    private javax.swing.JButton fundtransfer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField lasttransaction;
    private javax.swing.JButton ministatement;
    private javax.swing.JTextField name;
    private javax.swing.JButton pinchange;
    private javax.swing.JButton withdrawal;
    // End of variables declaration//GEN-END:variables
}
